# Generated by Django 3.1.4 on 2020-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='wage',
            field=models.IntegerField(default=50),
        ),
    ]
